### ISSUE TITLE
Hi How can I add sorting by date field

### ISSUE THREAD

**Issue by ailunbolinkenasi** [joaomlneto/jekyll-multiverse-template#3]
How can I add sorting by date field？

**Comment by joaomlneto** [comment]
Sorry! I completely missed your question here :(

You can alter the order by modifying this line in `/_layouts/multiverse.html`, inserting a [`sort` filter](https://shopify.github.io/liquid/filters/sort/).
https://github.com/joaomlneto/jekyll-multiverse-template/blob/5c67c266539a36d2e57403b50c28910e2dbd51be/_layouts/multiverse.html#L13

I haven't tested it, but something like:
```liquid
{% for image in site.images | sort: 'date' %}
```

You will then need to add a `date` property to each file in the `_images` folder. For example:

```md
---
title: Magna Feugiat Lorem
caption: Nunc blandit nisi ligula magna sodales lectus elementum non. Integer id venenatis velit.
date: 2023-08-19
---
```

If you want to show the date, you can modify how images are displayed in the layout:

https://github.com/joaomlneto/jekyll-multiverse-template/blob/master/_layouts/multiverse.html#L14-L20

For example, by replacing `{{ image.caption }}` with `{{image.date}} - {{ image.caption }}`.

There's other ways of doing it, but this is the most straightforward based on the existing code. :)
Let me know if you have any other questions!
